server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${USER_DB_NAME}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  kafka:
    producer:
      bootstrap-servers: localhost:29092

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/${REALM_NAME}

management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:5173, http://localhost:3000

minio:
  url: http://localhost:9005
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${USER_MINIO_BUCKET}

application:
  config:
    payment-url: http://localhost:8082

logging:
  level:
    com.ecommerce.usertenantservice.integration.payment.PaymentServiceClient: DEBUG