DROP TABLE IF EXISTS outbox;

CREATE TABLE outbox (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        aggregate_type  VARCHAR(100) NOT NULL,
                        aggregate_id    VARCHAR(255) NOT NULL,
                        message_type    VARCHAR(255) NOT NULL,
                        message_payload JSONB NOT NULL,
                        created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_outbox_created_at ON outbox(created_at);

ALTER TABLE inbox
    ADD COLUMN status          VARCHAR(50),
    ADD COLUMN retry_count     INTEGER DEFAULT 0,
    ADD COLUMN error_message   TEXT,
    ADD COLUMN received_at     TIMESTAMP WITHOUT TIME ZONE;

UPDATE inbox
SET status       = 'PROCESSED',
    retry_count  = 0,
    received_at  = COALESCE(processed_at, NOW())
WHERE status IS NULL;

ALTER TABLE inbox
    ALTER COLUMN status      SET NOT NULL,
    ALTER COLUMN received_at SET NOT NULL;

ALTER TABLE inbox
    ALTER COLUMN processed_at DROP NOT NULL,
    ALTER COLUMN processed_at DROP DEFAULT;