spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
  cloud:
    openfeign:
      circuit breaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 15000
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  config:
    import: optional:file:.env[.properties]

resilience4j:
  circuit breaker:
    instances:
      payment-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      payment-service:
        maxAttempts: 3
        waitDuration: 2s
  time limiter:
    instances:
      payment-service:
        timeoutDuration: 10s

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_ID}
      principal-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

application:
  clients:
    user-tenant:
      url: ${USER_TENANT_SERVICE_URL}