CREATE OR REPLACE FUNCTION update_modified_column()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- ─── orders ─────────────────────────────────────────────────────────────────

CREATE TABLE orders
(
    id                     BIGSERIAL      PRIMARY KEY,
    user_id                UUID           NOT NULL,
    tenant_id              BIGINT         NOT NULL,
    status                 VARCHAR(50)    NOT NULL,
    total_amount           DECIMAL(12, 2) NOT NULL,
    currency               VARCHAR(10)    NOT NULL DEFAULT 'TRY',
    shipping_address_json  TEXT           NOT NULL,
    payment_transaction_id VARCHAR(255),
    cancellation_reason    TEXT,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_orders_total  CHECK (total_amount > 0),
    CONSTRAINT chk_orders_status CHECK (
        status IN ('CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED')
    )
);

CREATE INDEX idx_orders_user        ON orders (user_id);
CREATE INDEX idx_orders_tenant      ON orders (tenant_id);
CREATE INDEX idx_orders_status      ON orders (status);
CREATE INDEX idx_orders_user_tenant ON orders (user_id, tenant_id);

CREATE TRIGGER update_orders_modtime
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- ─── order_items ─────────────────────────────────────────────────────────────

CREATE TABLE order_items
(
    id                BIGSERIAL      PRIMARY KEY,
    order_id          BIGINT         NOT NULL,
    tenant_id         BIGINT         NOT NULL,
    product_id        BIGINT         NOT NULL,
    sku               VARCHAR(100)   NOT NULL,
    product_name      VARCHAR(500)   NOT NULL,
    product_image_url TEXT,
    unit_price        DECIMAL(12, 2) NOT NULL,
    quantity          INTEGER        NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_order_items_qty   CHECK (quantity > 0),
    CONSTRAINT chk_order_items_price CHECK (unit_price > 0),
    CONSTRAINT fk_order_items_order  FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order          ON order_items (order_id);
CREATE INDEX idx_order_items_tenant_product ON order_items (tenant_id, product_id);

CREATE TRIGGER update_order_items_modtime
    BEFORE UPDATE ON order_items
    FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- ─── outbox ──────────────────────────────────────────────────────────────────

CREATE TABLE outbox
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(100)                NOT NULL,
    aggregate_id    VARCHAR(255)                NOT NULL,
    message_type    VARCHAR(255)                NOT NULL,
    message_payload JSONB                       NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_outbox_created_at ON outbox (created_at);

-- Debezium CDC için zorunlu: UPDATE/DELETE event'lerinde eski değerleri taşısın
ALTER TABLE outbox REPLICA IDENTITY FULL;

-- ─── inbox ───────────────────────────────────────────────────────────────────

CREATE TABLE inbox
(
    message_id    VARCHAR(255)                PRIMARY KEY,
    event_type    VARCHAR(255)                NOT NULL,
    payload       JSONB                       NOT NULL,
    status        VARCHAR(50)                 NOT NULL,
    retry_count   INTEGER DEFAULT 0,
    error_message TEXT,
    received_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    processed_at  TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_inbox_status  ON inbox (status);
CREATE INDEX idx_inbox_pending ON inbox (received_at) WHERE status = 'PENDING';
