CREATE OR REPLACE FUNCTION update_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id       UUID                                    NOT NULL,
    username          VARCHAR(255),
    email             VARCHAR(255)                            NOT NULL,
    first_name        VARCHAR(100),
    last_name         VARCHAR(100),
    user_type         VARCHAR(20)                             NOT NULL,
    is_active         BOOLEAN DEFAULT TRUE,
    email_verified    BOOLEAN DEFAULT FALSE,
    phone_number      VARCHAR(20),
    profile_image_url VARCHAR(500),
    language          VARCHAR(10),
    created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_users_user_type CHECK (user_type IN ('PLATFORM_ADMIN', 'USER'))
);

CREATE UNIQUE INDEX uk_users_email ON users (email);
CREATE UNIQUE INDEX uk_users_keycloak ON users (keycloak_id);
CREATE UNIQUE INDEX uk_users_username ON users (username) WHERE username IS NOT NULL;

CREATE TRIGGER trg_update_users_timestamp
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();


CREATE TABLE tenants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)                            NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    business_name VARCHAR(255)                            NOT NULL,
    tax_id        VARCHAR(50),
    business_type VARCHAR(20),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(20),
    description   TEXT,
    logo_url      VARCHAR(500),
    website_url   VARCHAR(255),
    is_verified   BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_tenants_status CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT chk_tenants_business_type CHECK (business_type IN ('INDIVIDUAL', 'CORPORATE'))
);

CREATE TRIGGER trg_update_tenants_timestamp
    BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();


CREATE TABLE user_tenants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                                  NOT NULL,
    tenant_id  BIGINT                                  NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_user_tenants_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_tenants_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT uk_user_tenant_relation UNIQUE (user_id, tenant_id),
    CONSTRAINT chk_user_tenants_role CHECK (role IN ('OWNER', 'ADMIN', 'STAFF', 'ACCOUNTANT'))
);

CREATE TRIGGER trg_update_user_tenants_timestamp
    BEFORE UPDATE ON user_tenants
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();


CREATE TABLE addresses
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT,
    tenant_id      BIGINT,
    address_type   VARCHAR(20),
    line1          VARCHAR(255)                            NOT NULL,
    line2          VARCHAR(255),
    city           VARCHAR(100),
    state_province VARCHAR(100),
    zip_code       VARCHAR(20),
    country        VARCHAR(3),
    recipient_name VARCHAR(100),
    phone_number   VARCHAR(20),
    is_default     BOOLEAN DEFAULT FALSE,
    label          VARCHAR(50),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    is_active      BOOLEAN DEFAULT TRUE,
    created_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at     TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_addresses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT chk_address_owner CHECK (user_id IS NOT NULL OR tenant_id IS NOT NULL),
    CONSTRAINT chk_address_type CHECK (address_type IN ('SHIPPING', 'BILLING', 'WAREHOUSE', 'REGISTERED'))
);

CREATE TRIGGER trg_update_addresses_timestamp
    BEFORE UPDATE ON addresses
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();


CREATE TABLE outbox
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type  VARCHAR(50)                             NOT NULL,
    aggregate_id    VARCHAR(255)                            NOT NULL,
    message_type    VARCHAR(255)                            NOT NULL,
    message_payload JSONB                                   NOT NULL,
    processed       BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT NOW(),
    sent_at         TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_outbox_pending ON outbox(created_at) WHERE processed = FALSE;