-- Kullanıcı aktivite/gezinme geçmişi: kişiselleştirilmiş öneri + AI servisini besleme için.
-- Şimdilik PRODUCT_VIEW; ileride FAVORITE/CART_ADD gibi sinyaller aynı tabloya eklenebilir.
CREATE TABLE user_activity (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       UUID        NOT NULL,
    activity_type VARCHAR(40)  NOT NULL,
    product_id    BIGINT,
    tenant_id     BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE
);

-- "Son gezilenler" + öneri sorguları için
CREATE INDEX idx_user_activity_user_created ON user_activity (user_id, created_at DESC);
CREATE INDEX idx_user_activity_user_product ON user_activity (user_id, product_id);
