global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'user-tenant-service:8081'
          - 'payment-service:8082'
          - 'product-service:8084'
          - 'search-service:8085'
          - 'basket-service:8086'
          - 'stock-service:8087'
          - 'api-gateway:9051'
          - 'mail-service:8089'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']