server:
  port: 9050

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/${REALM_NAME}

  cloud:
    gateway:
      routes:
        - id: search-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/public/search/**

        - id: user-tenant-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**, /api/v1/tenants/**, /api/v1/addresses/**

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/products/**, /api/v1/public/products/**, /api/v1/categories/**

        - id: basket-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/baskets/**

        - id: stock-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/stocks/**
