CREATE TABLE categories (
                            id BIGSERIAL PRIMARY KEY,
                            name VARCHAR(255) NOT NULL,
                            parent_id BIGINT,
                            slug VARCHAR(255) UNIQUE NOT NULL,
                            description VARCHAR(500),
                            image_url VARCHAR(500),
                            icon VARCHAR(100),
                            is_active BOOLEAN DEFAULT TRUE,
                            display_order INTEGER DEFAULT 0,
                            level INTEGER DEFAULT 0,
                            full_path VARCHAR(500),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL
);

CREATE INDEX idx_categories_parent ON categories(parent_id);

CREATE TABLE products (
                          id BIGSERIAL PRIMARY KEY,
                          tenant_id BIGINT NOT NULL,
                          category_id BIGINT NOT NULL,
                          parent_product_id BIGINT,

                          name VARCHAR(255) NOT NULL,
                          description TEXT,
                          sku VARCHAR(100) NOT NULL,
                          brand VARCHAR(100),

                          price DECIMAL(12,2) NOT NULL,
                          currency VARCHAR(3) DEFAULT 'TRY',
                          discount_percentage DECIMAL(5,2) DEFAULT 0.00,
                          discounted_price DECIMAL(12,2),

                          weight_grams INTEGER,
                          dimensions_cm VARCHAR(50),

                          main_image_url VARCHAR(500),
                          image_urls JSONB,
                          attributes JSONB,

                          status VARCHAR(50) DEFAULT 'ACTIVE',
                          sales_status VARCHAR(50) DEFAULT 'ON_SALE',

                          is_featured BOOLEAN DEFAULT FALSE,
                          view_count INTEGER DEFAULT 0,
                          sale_count INTEGER DEFAULT 0,
                          rating_average DECIMAL(3,2) DEFAULT 0.00,
                          review_count INTEGER DEFAULT 0,

                          min_order_qty INTEGER DEFAULT 1,
                          max_order_qty INTEGER,

                          ai_review_report TEXT,
                          tags JSONB,
                          seo_title TEXT,
                          seo_description TEXT,
                          seo_keywords TEXT,

                          created_by_user_id UUID,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories (id),
                          CONSTRAINT fk_product_parent FOREIGN KEY (parent_product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX idx_products_tenant ON products(tenant_id);
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_sku ON products(sku);

CREATE TABLE product_reviews (
                                 id BIGSERIAL PRIMARY KEY,
                                 product_id BIGINT NOT NULL,
                                 user_id UUID NOT NULL,

                                 review_text TEXT,
                                 rating INTEGER CHECK (rating >= 1 AND rating <= 5),
                                 title VARCHAR(255),

                                 sentiment_label VARCHAR(20),
                                 sentiment_score FLOAT,

                                 is_verified_purchase BOOLEAN DEFAULT FALSE,
                                 helpful_count INTEGER DEFAULT 0,
                                 not_helpful_count INTEGER DEFAULT 0,
                                 status VARCHAR(50) DEFAULT 'PENDING',

                                 reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 image_urls JSONB,
                                 keywords JSONB,

                                 seller_response TEXT,
                                 seller_response_at TIMESTAMP,

                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE INDEX idx_reviews_product ON product_reviews(product_id);
CREATE INDEX idx_reviews_user ON product_reviews(user_id);

CREATE TABLE outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        aggregate_type VARCHAR(100) NOT NULL,
                        aggregate_id VARCHAR(255) NOT NULL,
                        message_type VARCHAR(255) NOT NULL,
                        message_payload JSONB NOT NULL,

                        processed BOOLEAN NOT NULL DEFAULT FALSE,
                        retry_count INTEGER DEFAULT 0,
                        error_message TEXT,

                        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                        sent_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_outbox_unprocessed ON outbox(created_at) WHERE processed = FALSE;

CREATE TABLE inbox (
                       message_id VARCHAR(255) PRIMARY KEY,
                       event_type VARCHAR(255) NOT NULL,
                       payload JSONB NOT NULL,

                       status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
                       retry_count INTEGER DEFAULT 0,
                       error_message TEXT,

                       received_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                       processed_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX idx_inbox_status ON inbox(status);
CREATE INDEX idx_inbox_pending ON inbox(received_at) WHERE status = 'PENDING';