-- Helpful/unhelpful oy takibi — kullanıcı başına bir oy, tekrar tıklama engellenir
CREATE TABLE review_votes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id   BIGINT    NOT NULL REFERENCES product_reviews(id) ON DELETE CASCADE,
    user_id     UUID      NOT NULL,
    is_helpful  BOOLEAN   NOT NULL,
    voted_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_review_vote_per_user UNIQUE (review_id, user_id)
);

-- Yorum yazarının görünen adı (yazılma anında denormalize edilir, user-service çağrısı gerektirmez)
ALTER TABLE product_reviews ADD COLUMN reviewer_name VARCHAR(100);
