spring:
  application:
    name: mail-service
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: health,info
